.gitignore
working-with-content/adding-content/adding-events.rst
working-with-content/adding-content/adding-files.rst
working-with-content/adding-content/adding-pages.rst

Updating with robot-framework for image creation, we need more robots !

Add robot for picture creation

---

develop/plone/content/dexterity.rst

This fixes #160 
This is not really nice, yet but better than it was, we should remove the old document and include the full dexterity docs here, at the moment we have a mix of includes from the official dexterity docs which is better because of updates and some hand written older stuff.

Fix for 160

---

adapt-and-extend/theming/templates_css/template_basics.rst

Fix for issue 155

---

develop/addons/releasing.rst

While I do think checking passwords into version control is hardcore, this should probably say "hard-code"

"hardcore" -> "hard-code"

---

about/helper_tools.rst

Update vim part of docs with second plugin. which is easier to use, but has less functions

Update vim part

---

working-with-content/managing-content/ploneformgen/embedding.rst

Adding a missing portion of a tag.

Add missing "structure" to tal

---

manage/installing/installation.rst

This will fix the broken reference link

Fix for #219

---

develop/addons/components/adapters.rst
working-with-content/adding-content/adding-events.rst
working-with-content/adding-content/adding-files.rst
working-with-content/adding-content/adding-pages.rst

fixes https://github.com/plone/documentation/issues/225

fix some of the screenshots, and broken links.

---

develop/addons/releasing.rst

Fix for #110

---

develop/addons/upgrade_to_50.rst

That's just work-in-progress but maybe that would be better to merge it into the 5.0 branch immediately (so people can find it more easily and contribute).
Up to you.

Upgrading a custom add-on to 5.0 (WIP)

---

about/styleguide.rst

This adds information how to use gists

[ci skip] Add info about gists

---

manage/installing/hotfixes.rst
manage/installing/index.rst

closes https://github.com/plone/documentation/issues/259

document where to find hotfixes

---

about/history/20150518.rst
about/index.rst

This adds the changelog for the upcoming release of the docs.

[ci skip] Added changelog

---

about/history/20150518.rst

[ci skip]: Update Changelog with latest commits

---

manage/deploying/production/ubuntu_production.rst
manage/installing/installation.rst

Update installer docs to latest version

docs: Update Plone version to 4.3.5

---

develop/plone/misc/zope_debug_prompt.rst

Idea from @vangheezy creating repository: https://twitter.com/vangheezy/status/614416314594131968

Using the Zope debug prompt with Plone.

---

develop/plone/getstarted/index.rst
develop/plone/i18n/internationalisation.rst
develop/plone/members/member_profile.rst
develop/plone/searching_and_indexing/indexing.rst
manage/troubleshooting/exceptions.rst
manage/upgrading/troubleshooting.rst

- fixed broken links
- fixed typos
- fixed rst

P5 dev.plone.org links

---

_robot.rst
working-with-content/adding-content/adding-events.rst

P5 screenshot 1

---

quickstart/index.rst

Update for Plone 5

---

develop/addons/schema-driven-forms/creating-a-simple-form/creating-a-package.rst
develop/addons/schema-driven-forms/creating-a-simple-form/creating-a-schema.rst
develop/addons/schema-driven-forms/creating-a-simple-form/creating-the-form-view.rst
develop/plone/forms/files.rst
develop/plone/forms/manual.rst
develop/plone/forms/wysiwyg.rst
develop/plone/forms/z3c.form.rst
develop/plone/functionality/controlpanel.rst
develop/plone/i18n/translating_content.rst
develop/plone/misc/html.rst
develop/plone/serving/http_request_and_response.rst
develop/plone/views/browserviews.rst

I've updated all pages, zcml is used instead of grok.

Converted all grok references to zcml

---

about/helper_tools.rst
about/searching.rst

- add link to sublime video
- add new site about searching tools

Add youtube link

---

develop/plone/content/behaviors.rst
develop/plone/content/creating.rst
develop/plone/content/importexport.rst
develop/plone/forms/files.rst
develop/plone/forms/wysiwyg.rst
develop/plone/forms/z3c.form.rst
develop/plone/functionality/portlets.rst
develop/plone/i18n/translating_content.rst
develop/plone/images/templates.rst
develop/plone/misc/html.rst
develop/plone/misc/index.rst
develop/plone/misc/paster_templates.rst
develop/plone/serving/publishing.rst
develop/plone/sessions/login.rst
develop/plone/views/viewlets.rst

Reverts plone/documentation#326

Revert "Update svn links"

---

manage/installing/installation.rst

- Update install docs to latest Plone 4 version
- add a note about using ZopeSkel for install part [we still need to improve that note :) ]

Update Plone version, add note

---

README.rst

Fix for #333 
- Update README to follow best practices
- Update links in README
- Update part about installation 
- Add note about Operating Systems, where it is tested on

Update README, fix for #333

---

develop/plone/security/custom_permissions.rst

Typo in rolemap
